<a href="https://colab.research.google.com/github/stac-bot/pythonic/blob/main/List_Comprehensions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Using Comprehension insteaded of map and filters

**what is comprehension?** <br>

python provides a special syntax, called *comprehension*, for succinctly iterating through these types and creating derivative data structures. In more simple way to put this is, it is an expression that helps to derivate new list from another sequence or iterable. This expression are called list comprehensions<br>
**what does comprehension do?**<br>
Comprehension can significantly increase the readability of the code and comes with other several benefits.

In [ ]:
# Example
li = [1,2,3,4,5,6]
# if i want the list of square for items in list a
# using list comprehension
result = [x**2 for x in li]
result

[1, 4, 9, 16, 25, 36]

Unless you're applying a single-argument function, list comprehensions are also cleaner than the map built-in fucntion for simple cases.
*map* requires the creation of lambda function for the computation, which is messy or noisy:

In [ ]:
alt = map(lambda x: x**2, li)
list(alt)

[1, 4, 9, 16, 25, 36]

Unlike *map*, list *comprehensio* let you easily apply conditions over the iteration or sequence being applied to:

In [ ]:
even_square = [x**2 for x in li if x%2==0]
even_square

[4, 16, 36]

the *filter* built-in function can be used along with *map* to achieve the same outcome, but it is much harder to read as compare to *list comprehension*:

In [ ]:
# map(fun,list)
# list = filter(func,iterable)
alt = map(lambda x:x**2,filter(lambda x: x%2==0, li))
list(alt)


[4, 16, 36]

Dictionaries and sets have their own list comprehension which is in many way similar to list comprehension except enclosed in {} braces instead of [] braces:
These makes it easy to create other types of derivative data Structure when writing algorithms:

In [ ]:
# {k:v for k,v in dict if condn}
even_square_dict = {x:x**2 for x in li if x%2==0}
# {exp(var) for var in li}
cube_set = {x**3 for x in li if x%3==0}
print(even_square_dict)
print(cube_set)


{2: 4, 4: 16, 6: 36}
{216, 27}


Using *map* and *filter* for sets and dictionary makes things bit more complicated indeed breaking them up across multiple lines, which is even noisier, and should be avoided:


In [ ]:
comp_dict = dict(map(lambda x: (x,x**2),
                     filter(lambda x: x%2==0, li)))
comp_set = set(map(lambda x: x**3, 
                   filter(lambda x: x%3==0, li)))
print(comp_dict)
print(comp_set
      )

{2: 4, 4: 16, 6: 36}
{216, 27}


**things to remember**


*   List comprehension are cleaner and simpler than *map* and *filter* built-in func because they don't require *lambda* expression
*   List comprehension allow you to easily skip items from the input list, a behavior that *map* doesn't support without *filter*.
*     Dictionaries and sets may also be created using comprehensions.
*     Avoid more than two control subexpression in comprehensions



Let's explore the last point!

Beyond the basic usage you can use comprehension for multiple levels of looping:

In [ ]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
result = [item for row in matrix for item in row]
result


[1, 2, 3, 4, 5, 6, 7, 8, 9]

this is simple and reasonable usage of multiple loops in a comprehesion.
Another thing we can do is replicating the two-level-deep layout:

In [ ]:
squared = [[x**2 for x in row] for row in matrix ]
squared

[[1, 4, 9], [16, 25, 36], [49, 64, 81]]

If above computation included another loop it would get so long that i've to split into multiple lines:

In [ ]:
import numpy as np
matrix = np.arange(12).reshape((3,2,2))
result = [x for row1 in matrix
          for row2 in row1
          for x in row2]
print(matrix)          
result

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

As we can see above, the multiline compreshension isn't much shorter than the alternative. Instead using the normal version of loops makes it clean and simple to understand:

In [ ]:
simple =[]
for i in matrix:
  for j in i:
    simple.extend(j)

simple

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

Comprehesion also support multiple *if conditons* . Multiple condition at same loop level makes it implicit and expression:

In [ ]:
a = np.arange(10)
b = [x for x in a if x>2 if x %2==0]
b

[4, 6, 8]

if condition can also be applied to all levels of loop 



In [ ]:
matrix = np.arange(12).reshape((3,4))
result2 = [[x for x in row if x%3==0] 
           for row in matrix if sum(row)>10]
result2

[[6], [9]]

**Things to remember**
*   Comprehension support multiple levels of loops and multiple conditions per loop level
*   Comprehesions with more than two control expressions are very difficult to read and should be avoided.

**It it not the end, there are many ways to use list comprehension. I will try bring some more as I'm curious to dive deep, let me know any pythonic way you would think is better.**